"""create table

Revision ID: 06707b10289b
Revises: 
Create Date: 2026-04-02 21:10:06.601660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06707b10289b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('warehouses', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('local_id')
    )
    op.create_table('ingredients',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('count_usages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('local_id')
    )
    op.create_table('products',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('local_id')
    )
    op.create_table('stock_items',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('local_id'),
    sa.UniqueConstraint('branch_id', 'stock_id', 'product_id', name='unique_stock_item')
    )
    op.create_index('ix_stock_items_product_id', 'stock_items', ['product_id'], unique=False)
    op.create_index('ix_stock_lookup', 'stock_items', ['branch_id', 'stock_id'], unique=False)
    op.create_table('transactions',
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('is_arrival', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('local_id')
    )
    op.create_index('ix_transactions_branch_timestamp', 'transactions', ['branch_id', 'timestamp'], unique=False)
    op.create_index('ix_transactions_timestamp', 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_timestamp', table_name='transactions')
    op.drop_index('ix_transactions_branch_timestamp', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_stock_lookup', table_name='stock_items')
    op.drop_index('ix_stock_items_product_id', table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_table('products')
    op.drop_table('ingredients')
    op.drop_table('branches')
    # ### end Alembic commands ###
